[package]
name = "bene-app"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["shell-open"] }
serde = { workspace = true }
serde_json = "1.0"
clap = { version = "4.4.11", features = ["derive"] }
env_logger = "0.10.1"
tokio = { workspace = true, features = ["full"] }
bene-epub = { path = "../bene-epub" }
anyhow = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
specta = { workspace = true }
tauri-specta = { version = "=2.0.0-rc.4", features = ["javascript", "typescript"] }
mediatype = { workspace = true }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
